const ActionTypes = {
    ADD_TODO: "ADD_TODO",
    REMOVE_TODO: "REMOVE_TODO",
    EDIT_TODO: "EDIT_TODO",
    CLEAR_ALL_TODOS: "CLEAR_ALL_TODOS",
    UPDATE_TODOS: "UPDATE_TODOS",
    USER_SIGN_IN: "USER_SIGN_IN",
    USER_SIGN_OUT: "USER_SIGN_OUT",
    USER_REGISTERED: "USER_REGISTERED",
    SHOW_LOADER: "SHOW_LOADER",
    HIDE_LOADER: "HIDE_LOADER",
    SHOW_ERROR: "SHOW_ERROR",
    HIDE_ERROR: "HIDE_ERROR",
    SHOW_CONGRTATS: "SHOW_CONGRTATS",
    HIDE_CONGRTATS: "HIDE_CONGRTATS"
}

export default ActionTypes;